-- Sample student dataset source of truth for ambassador seeding
-- Columns: name, major, minor, year, involvement_level
WITH ambassador_dataset(name, major, minor, year, involvement_level) AS (
    VALUES
        ('Ava Thompson', 'Marketing', 'Psychology', 'Freshman', 'High'),
        ('Liam Carter', 'Finance', 'Data Analytics', 'Sophomore', 'Medium'),
        ('Sophia Nguyen', 'Biology', 'Chemistry', 'Junior', 'High'),
        ('Noah Bennett', 'Computer Science', 'Mathematics', 'Senior', 'Low'),
        ('Isabella Flores', 'Fashion Merchandising', 'Business Analytics', 'Sophomore', 'High'),
        ('Ethan Brooks', 'Accounting', 'Information Systems', 'Junior', 'Medium'),
        ('Mia Patel', 'Nursing', 'Public Health', 'Freshman', 'Low'),
        ('Jackson Reed', 'Economics', 'Political Science', 'Senior', 'High'),
        ('Chloe Sanders', 'Communication Studies', 'Digital Media', 'Junior', 'Medium'),
        ('Lucas Kim', 'Engineering', 'Physics', 'Sophomore', 'Low'),
        ('Harper Collins', 'English', 'Creative Writing', 'Senior', 'High'),
        ('Aiden Murphy', 'Supply Chain Management', 'International Business', 'Freshman', 'Medium'),
        ('Ella Ramirez', 'Education', 'Spanish & Hispanic Studies', 'Junior', 'Low'),
        ('Mason Hughes', 'Real Estate', 'Finance', 'Sophomore', 'High'),
        ('Lily Foster', 'Psychology', 'Sociology', 'Senior', 'Medium'),
        ('Caleb Ward', 'Business Information Systems', 'Data Analytics', 'Junior', 'High'),
        ('Grace Kim', 'Biochemistry', 'Biology', 'Sophomore', 'Medium'),
        ('Dylan Price', 'Political Science', 'History', 'Freshman', 'Low'),
        ('Natalie Cruz', 'Strategic Communication', 'Marketing', 'Senior', 'High'),
        ('Owen Hayes', 'Mathematics', 'Computer Science', 'Junior', 'Medium'),
        ('Brooke Simmons', 'Interior Design', 'Studio Art', 'Sophomore', 'High'),
        ('Connor Blake', 'Management', 'Entrepreneurship', 'Freshman', 'Medium'),
        ('Zoe Patel', 'Nutritional Sciences', 'Kinesiology', 'Senior', 'Low'),
        ('Ryan Mitchell', 'Physics', 'Mathematics', 'Junior', 'High'),
        ('Madison Lee', 'Graphic Design', 'Design', 'Sophomore', 'Medium'),
        ('Tyler Scott', 'Military Science', 'Political Science', 'Freshman', 'Low'),
        ('Hannah Davis', 'Sociology', 'Women & Gender Studies', 'Senior', 'High'),
        ('Jake Turner', 'Finance', 'Economics', 'Junior', 'Medium'),
        ('Olivia Green', 'Dance', 'Theatre', 'Sophomore', 'High'),
        ('Andrew Cooper', 'Computer Science', 'Data Analytics', 'Freshman', 'Low'),
        ('Claire Watson', 'Religion', 'Philosophy', 'Senior', 'Medium'),
        ('Zachary Long', 'Supply Chain Management', 'Business Analytics', 'Junior', 'High'),
        ('Paige Bennett', 'Speech-Language Pathology', 'Kinesiology', 'Sophomore', 'Medium'),
        ('Brandon Ross', 'Engineering', 'Mathematics', 'Freshman', 'Low'),
        ('Sydney Howard', 'Journalism', 'English', 'Senior', 'High'),
        ('Kevin Nguyen', 'Data Science / Digital Culture & Data Analytics', 'Computer Science', 'Junior', 'Medium'),
        ('Lauren Price', 'Early Childhood Education', 'Educational Studies', 'Sophomore', 'High'),
        ('Trevor Hall', 'Economics', 'Finance', 'Freshman', 'Low'),
        ('Julia Brooks', 'Theatre', 'Creative Writing', 'Senior', 'Medium'),
        ('Cameron White', 'Actuarial Science', 'Mathematics', 'Junior', 'High'),
        ('Megan Kelly', 'Environmental Science & Sustainability', 'Environmental Science', 'Sophomore', 'Medium'),
        ('Austin Gray', 'Accounting', 'Finance', 'Freshman', 'Low'),
        ('Rachel Adams', 'Spanish & Hispanic Studies', 'Sociology', 'Senior', 'High'),
        ('Eric Foster', 'Geology', 'Environmental Science', 'Junior', 'Medium'),
        ('Sarah Bell', 'Anthropology', 'Comparative Race & Ethnic Studies', 'Sophomore', 'High'),
        ('Justin Parker', 'Marketing', 'Entrepreneurship', 'Freshman', 'Medium'),
        ('Emily Reed', 'Nursing', 'Nutritional Sciences', 'Senior', 'Low'),
        ('Dylan Hayes', 'Management', 'Political Science', 'Junior', 'High'),
        ('Katie Long', 'Art History', 'Studio Art', 'Sophomore', 'Medium'),
        ('Sean Murphy', 'Computer Science', 'Mathematics', 'Freshman', 'Low'),
        ('Abigail Turner', 'Women & Gender Studies', 'Sociology', 'Senior', 'High'),
        ('Luke Sanders', 'Physics', 'Astronomy', 'Junior', 'Medium'),
        ('Vanessa Cruz', 'Strategic Communication', 'Marketing', 'Sophomore', 'High'),
        ('Cole Bennett', 'Ranch Management', 'Business', 'Freshman', 'Low'),
        ('Brianna Scott', 'Kinesiology', 'Athletic Training', 'Senior', 'Medium'),
        ('Jordan Price', 'Finance', 'Accounting', 'Junior', 'High'),
        ('Lily Nguyen', 'Fashion Merchandising', 'Design', 'Sophomore', 'Medium'),
        ('Matthew Davis', 'Engineering', 'Computer Science', 'Freshman', 'Low'),
        ('Sophia Green', 'Creative Writing', 'English', 'Senior', 'High'),
        ('Tyler Brooks', 'Supply Chain Management', 'Business Analytics', 'Junior', 'Medium'),
        ('Emma Collins', 'Biology', 'Chemistry', 'Sophomore', 'High'),
        ('Jack Wilson', 'Economics', 'Data Analytics', 'Freshman', 'Medium'),
        ('Grace Turner', 'Education', 'Youth Advocacy', 'Senior', 'Low'),
        ('Alex Kim', 'Data Science / Digital Culture & Data Analytics', 'Mathematics', 'Junior', 'High'),
        ('Natalie White', 'Journalism', 'Political Science', 'Sophomore', 'Medium'),
        ('Ryan Adams', 'Accounting', 'Finance', 'Freshman', 'Low'),
        ('Chloe Hall', 'Interior Design', 'Design', 'Senior', 'High'),
        ('Ethan Parker', 'Computer Science', 'Data Analytics', 'Junior', 'Medium'),
        ('Madison Scott', 'Nursing', 'Kinesiology', 'Sophomore', 'High'),
        ('Logan Reed', 'Military Science', 'History', 'Freshman', 'Low'),
        ('Bella Martinez', 'Spanish & Hispanic Studies', 'Latinx Studies', 'Senior', 'High'),
        ('Carter Hughes', 'Management', 'Entrepreneurship', 'Junior', 'Medium'),
        ('Savannah Price', 'Environmental Earth Resources', 'Environmental Science', 'Sophomore', 'High'),
        ('Noah Gray', 'Mathematics', 'Actuarial Science', 'Freshman', 'Low'),
        ('Hailey Foster', 'Communication Studies', 'Sociology', 'Senior', 'Medium'),
        ('Ben Cooper', 'Finance', 'Business Analytics', 'Junior', 'High'),
        ('Kayla Watson', 'Theatre', 'Dance', 'Sophomore', 'Medium'),
        ('Mason Kelly', 'Engineering', 'Physics', 'Freshman', 'Low')
)
SELECT name, major, minor, year, involvement_level FROM ambassador_dataset;
